### ISSUE TITLE
Use apt addon in travis.yml

### ISSUE THREAD

**Issue by m1kc** [m1kc/lake#16]
``` yaml
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - gcc-4.8
   - g++-4.8
```
